@echo off
echo Pokrecem composer install...
composer install

echo Generisem app key...
php artisan key:generate

echo Pokrecem migracije...
php artisan migrate

echo Pokrecem Laravel development server...
php artisan serve --host=127.0.0.1 --port=8000

echo Server je pokrenut. Pritisni bilo koji taster za kraj...
pause
